[package]
name = "bevy_starter_project"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.6"
lazy_static = "1.4"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"